### ISSUE TITLE
termux-sms-send does not work. How to troubleshoot?

### ISSUE THREAD

**Issue by monperrus** [termux/termux-api#191]
termux-sms-send does not send any message.

How to debug? Are there logs to look at?

**Comment by monperrus** [comment]
Used adb.

The reason was that `android.permission.READ_PHONE_STATE` was not granted.

Fixed it in the permission settings, now it works.

```
07-06 22:17:21.421 24005 24511 E termux-api: Error in ResultReturner
07-06 22:17:21.421 24005 24511 E termux-api: java.lang.SecurityException: Neither user 10056 nor current process has android.permission.READ_PHONE_STATE.
07-06 22:17:21.421 24005 24511 E termux-api: 	at android.os.Parcel.readException(Parcel.java:1942)
07-06 22:17:21.421 24005 24511 E termux-api: 	at android.os.Parcel.readException(Parcel.java:1888)
07-06 22:17:21.421 24005 24511 E termux-api: 	at com.android.internal.telephony.ISms$Stub$Proxy.sendTextForSubscriber(ISms.java:789)
07-06 22:17:21.421 24005 24511 E termux-api: 	at android.telephony.SmsManager.sendTextMessageInternal(SmsManager.java:382)
07-06 22:17:21.421 24005 24511 E termux-api: 	at android.telephony.SmsManager.sendTextMessage(SmsManager.java:365)
07-06 22:17:21.421 24005 24511 E termux-api: 	at android.telephony.SmsManager.sendMultipartTextMessageInternal(SmsManager.java:571)
07-06 22:17:21.421 24005 24511 E termux-api: 	at android.telephony.SmsManager.sendMultipartTextMessage(SmsManager.java:537)
07-06 22:17:21.421 24005 24511 E termux-api: 	at com.termux.api.SmsSendAPI$1.writeResult(SmsSendAPI.java:32)
07-06 22:17:21.421 24005 24511 E termux-api: 	at com.termux.api.util.ResultReturner$1.run(ResultReturner.java:112)
07-06 22:17:21.421 24005 24511 E termux-api: 	at java.lang.Thread.run(Thread.java:764)
07-06 22:17:46.386 20144 20144 D WindowClient: Remove from mViews: DecorView@b342c28[TermuxActivity], this = android.view.WindowManagerGlobal@511e604
```

**Comment by SwapnilPamecha** [comment]
Can you please elaborate? how did you solve this issue? I'm facing the same on my android.

**Comment by xeffyr** [comment]
@SwapnilPamecha 
> Used adb.
The reason was that android.permission.READ_PHONE_STATE was not granted.

**Comment by frankline-nfor** [comment]
Please I can't send sms using termux. Each time I try there is an error that says: no recipent number given. So I don't know what to do. Someone talked of allowing android permission. How can I do this exactly please??
