### ISSUE TITLE
Termux:API crashes on certain commands (Samsung Galaxy S5 mini)

### ISSUE THREAD

**Issue by Supersebi3** [termux/termux-api#207]
When using certain commands, the Termux\:API app crashes and any further termux-api command calls will just do nothing. I tried force stopping Termux and Termux\:API, cleared cache, and even rebooted phone. Nothing worked. This happened to me on the following occasions:

- `termux-brightness 25` - Error message saying that Termux\:API needs permission to write phone settings, which I can't provide as my device is not rooted. Maybe making it request device administrator permissions can help here?
- `termux-dialog` with no apparent error message
- `termux-fingerprint` also with no error message

**Comment by dkramer95** [comment]
@Supersebi3 Which version of Android are you running?

**Comment by Supersebi3** [comment]
@dkramer95 6.0.1

**Comment by Supersebi3** [comment]
update: i tried `termux-dialog confirm -t "stuff" -i "stuff"`, got window saying Termux:API crashed, stopped the command with ctrl-c, but could still use termux-api commands afterwards

**Comment by isrgish** [comment]
I'm experiencing the same problem. When I tried the first time to run `termux-dialog` I got a notification that Termux:API stopped working. Since then it just hangs when I try again. Some other api's work fine (even after this problem) like clipboard etc..

**Comment by Supersebi3** [comment]
@isrgish yeah, clipboard works fine for me too

**Comment by pawamoy** [comment]
Happens to me when I try to use `termux-speech-to-text` on Android 8.1.0.

Sometimes the other commands still work after (like `termux-dialog` and `termux-notification`) but sometimes the API is really crashes and no `termux-` command work after.

**Comment by perlpunk** [comment]
Happened to me too. `pkg uninstall termux-api && pkg install termux-api` at least make the other commands work again.
Android 6.0.1, same phone.

**Comment by perlpunk** [comment]
@xeffyr no, `pgk upgrade` wouldn't have fixed it, because I had already the newest version. I was on a fresh install, tried several api commands, then tried `termux-brightness` and `termux-dialog`, and after that most other api commands didn't work anymore (just hung).

**Comment by sgeto** [comment]
Same here (Samsung Galaxy note 8.1 running Android 7.1.2)
I made a stacktrace, hope it helps:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setTint(int)' on a null object reference
	at com.termux.api.ToastAPI$1$1.run(ToastAPI.java:38)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

**Comment by laconbass** [comment]
> Termux:API needs permission to write phone settings, which I can't provide as my device is not rooted. Maybe making it request device administrator permissions can help here?

@Supersebi3 This permissions can be manually activated at settings>apps>special access (last option at bottom)

Don't know why the app does not ask automatically for them.
