### ISSUE TITLE
Missing class file (incorrect name?)

### ISSUE THREAD

**Issue by CtrlAltCuteness** [termux/termux-api#217]
Android 5.1.1
Rooted, Xposed, Custom ROM (obsolete)

Worked fine before a certain update. I tried both setups (pure Google Play and pure F-Droid) and both yield the same result.

```
java.lang.ClassNotFoundException: Didn't find class "com.example.termuxam.Am" on path: DexPathList[[zip file "/data/data/com.termux/files/usr/libexec/termux-am/am.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        Suppressed: java.io.IOException: Failed to open oat file from dex location '/data/data/com.termux/files/usr/libexec/termux-am/am.apk'
                at dalvik.system.DexFile.openDexFileNative(Native Method)
                at dalvik.system.DexFile.openDexFile(DexFile.java:295)
                at dalvik.system.DexFile.<init>(DexFile.java:80)
                at dalvik.system.DexFile.<init>(DexFile.java:59)
                at dalvik.system.DexPathList.loadDexFile(DexPathList.java:262)
                at dalvik.system.DexPathList.makeDexElements(DexPathList.java:231)
                at dalvik.system.DexPathList.<init>(DexPathList.java:109)
                at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
                at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:38)
                at java.lang.ClassLoader.createSystemClassLoader(ClassLoader.java:128)
                at java.lang.ClassLoader.access$000(ClassLoader.java:65)
                at java.lang.ClassLoader$SystemClassLoader.<clinit>(ClassLoader.java:81)
                at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:137)
        Caused by: java.io.IOException: Failed to open oat file from /data/data/com.termux/files/usr/libexec/termux-am/arm/am.odex (error Failed to open oat filename for reading: No such file or directory) (no dalvik_cache availible) and relocation failed.
                ... 13 more
        Caused by: java.io.IOException:
                ... 13 more
        Caused by: java.io.IOException: Failed to remove obsolete file from /data/dalvik-cache/arm/data@data@com.termux@files@usr@libexec@termux-am@am.apk@classes.dex when searching for dex file /data/data/com.termux/files/usr/libexec/termux-am/am.apk: Permission denied
                ... 13 more
        Suppressed: java.lang.ClassNotFoundException: com.example.termuxam.Am
                at java.lang.Class.classForName(Native Method)
                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                ... 1 more
        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by Grimler91** [comment]
Does it happen for all api commands? 
What's the output of `ls -lR /data/data/com.termux/files/usr/libexec/termux-am/`?

**Comment by xeffyr** [comment]
> Caused by: java.io.IOException: Failed to remove obsolete file from /data/dalvik-cache/arm/data@data@com.termux@files@usr@libexec@termux-am@am.apk@classes.dex when searching for dex file /data/data/com.termux/files/usr/libexec/termux-am/am.apk: Permission denied
                ... 13 more

The problem is that DalvikVM cannot remove old cache file for am.apk. Since the updated file can't be created, you getting `java.lang.NoClassDefFoundError`.

As solution, I suggest to wipe dalvik cache from recovery.

**Comment by CtrlAltCuteness** [comment]
Should I reinstall Termux as I have done this to it in the past:
```bash
chmod -R go-rwx /data/data/com.termux/files
```

**Comment by Grimler91** [comment]
@CtrlAltCuteness Reinstalling/chmod'ding termux won't help if the dalvik-cache is the problem. 
You'll need to boot to recovery as suggested by @xeffyr and clear it from there.

I wonder why this happened in the first place..

**Comment by CtrlAltCuteness** [comment]
I uninstalled Termux and every add-on for it (backed up files I wanted to keep, of course). After that, I cleared the Davlik Cache, waited for it to boot, then reinstalled everything.

Note that only Termux and root could access that path at the time I had the issues, which is what I meant by I used `chmod` (past tense).

Commenting and closing due to user error. Sorry about that. ^w^;
