### ISSUE TITLE
Termux-dialog stopped working after version 0.25

### ISSUE THREAD

**Issue by xandro0777** [termux/termux-api#227]
Any termux-dialog invocation leads to "unfortunately termux:api has stopped"

Downgrading to 0.25 fixes that. 

Android 5.1

**Comment by xandro0777** [comment]
Got a logcat and found presumably the same problem as #228:

```
Process: com.termux.api, PID: 22020
E/AndroidRuntime(22020): java.lang.RuntimeException: Unable to start receiver com.termux.api.TermuxApiReceiver: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
E/AndroidRuntime(22020):        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2646)
E/AndroidRuntime(22020):        at android.app.ActivityThread.access$1700(ActivityThread.java:155)
E/AndroidRuntime(22020):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
E/AndroidRuntime(22020):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(22020):        at android.os.Looper.loop(Looper.java:135)
```
