### ISSUE TITLE
termux-telephony-cellinfo not working

### ISSUE THREAD

**Issue by Ampli-fier** [termux/termux-api#307]
**Problem description**
The command `termux-telephony-cellinfo` is not showing any information.
Errors are logged to logcat.

**Steps to reproduce**

```
$ termux-telephony-cellinfo
[$
```

**Expected behavior**
Cell information is shown properly.

**Additional information**

- termux-api v0.38

- Location permission is granted

- termux-info
```
$ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.148-g02e4d6af1113-ab5555671 #0 SMP PREEMPT Fri May 10 20:41:11 UTC 2019 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 3
$
```

- logcat

```
mm:46.637 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10158 <<<<<<
mm:46.718 D AndroidRuntime: Calling main entry com.example.termuxam.Am
mm:46.736 E termux-api: Error in ResultReturner
mm:46.736 E termux-api: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
mm:46.736 E termux-api:    at com.termux.api.TelephonyAPI$1.writeJson(TelephonyAPI.java:37)
mm:46.736 E termux-api:    at com.termux.api.util.ResultReturner$ResultJsonWriter.writeResult(ResultReturner.java:88)
mm:46.736 E termux-api:    at com.termux.api.util.ResultReturner.lambda$returnData$0(ResultReturner.java:133)
mm:46.736 E termux-api:    at com.termux.api.util.-$$Lambda$ResultReturner$oCU8JqHW5HLMrNZa40ThjAWcwzo.run(Unknown Source:8)
mm:46.736 E termux-api:    at java.lang.Thread.run(Thread.java:764)
mm:46.737 D AndroidRuntime: Shutting down VM
```

**Comment by agnostic-apollo** [comment]
This should have been solved with 67954de3. Install latest version and try again. Make sure to enable location if on Android 8+.

https://github.com/termux/termux-api/blob/v0.38/app/src/main/java/com/termux/api/TelephonyAPI.java#L37
