### ISSUE TITLE
[SDK-29] termux-telephony-deviceinfo output is truncated

### ISSUE THREAD

**Issue by xeffyr** [termux/termux-api#362]
**Problem description**

Android 10 restricts access to device identifiers, thus IMEI no longer can be read and exception is being thrown.

![Screenshot_20200809-181128_Termux](https://user-images.githubusercontent.com/25881154/89735627-abb04300-da6c-11ea-98c4-dc6660e42632.png)

**Steps to reproduce**
1. Build Termux app with target and compile SDK levels of `29`.
2. Build Termux:API of target and compile SDK levels of `29`.
3. Perform clear installation of both apps on device. If not using Lineage OS, `setenforce 0` is needed to fix `execve()`.
4. Install `termux-api` and run `termux-telephony-deviceinfo`.

**Expected behavior**
If exception was occurred, it should be caught and related value should not be displayed. IMEI in this case can be returned as `000000000000000` (15 zeros) if we want maintain backwards compatibility.

**Additional information**

* Termux application version: latest git
* Android OS version: 10
* Device model: SM-G930FD

Log:
```
08-09 18:11:22.353 19955 20026 E termux-api: Error in ResultReturner
08-09 18:11:22.353 19955 20026 E termux-api: java.lang.SecurityException: getDeviceId: The user 10149 does not meet the requirements to access device identifiers.
08-09 18:11:22.353 19955 20026 E termux-api: 	at android.os.Parcel.createException(Parcel.java:2071)
08-09 18:11:22.353 19955 20026 E termux-api: 	at android.os.Parcel.readException(Parcel.java:2039)
08-09 18:11:22.353 19955 20026 E termux-api: 	at android.os.Parcel.readException(Parcel.java:1987)
08-09 18:11:22.353 19955 20026 E termux-api: 	at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:10590)
08-09 18:11:22.353 19955 20026 E termux-api: 	at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:1619)
08-09 18:11:22.353 19955 20026 E termux-api: 	at com.termux.api.TelephonyAPI$2.writeJson(TelephonyAPI.java:170)
08-09 18:11:22.353 19955 20026 E termux-api: 	at com.termux.api.util.ResultReturner$ResultJsonWriter.writeResult(ResultReturner.java:88)
08-09 18:11:22.353 19955 20026 E termux-api: 	at com.termux.api.util.ResultReturner.lambda$returnData$0(ResultReturner.java:133)
08-09 18:11:22.353 19955 20026 E termux-api: 	at com.termux.api.util.-$$Lambda$ResultReturner$oCU8JqHW5HLMrNZa40ThjAWcwzo.run(Unknown Source:8)
08-09 18:11:22.353 19955 20026 E termux-api: 	at java.lang.Thread.run(Thread.java:919)
```

**Comment by xeffyr** [comment]
Fixed by https://github.com/termux/termux-api/pull/375.

**Comment by xeffyr** [comment]
Changed target SDK to 29 - doesn't fix.
