### ISSUE TITLE
`termux-camera-photo` not working

### ISSUE THREAD

**Issue by honnzoun** [termux/termux-api#435]
**Problem description**
When I use `termux-camera-photo -c 1 photo.jpg` I dont get any errors but the file is emty 0Bytes.

**Steps to reproduce**
`termux-camera-photo -c 0 photo.jpg ` or `termux-camera-photo photo.jpg `

**Expected behavior**
I want to take picture from my old phone so I can use it as "security camera"

**Additional information**

* Termux application version: 0.117
* Android OS version: 7.1.2
* Device model: xiaomi redmi 4x

**Comment by florinbuda85** [comment]
I have the same problem on:

 OS: Android 10 aarch64
 Host: Nokia Nokia 5.1
 Kernel: 3.18.119+

**Comment by Toskan4134** [comment]
I have the same problem :(

**Comment by Alisa900** [comment]
I have the same problem

Device: Samsung Galaxy J5 2016
OS: Android 7.1.1 ( armeabi-v7a )
Kernel: 3.10.49
Termux-API ( Application ): 0.49 ( F-Droid )
Termux-API: 0.56

Crash log:
```
09-30 20:44:25.766  9555  9555 D AndroidRuntime: Calling main entry com.termux.termuxam.Am
09-30 20:44:25.926  3484  9564 I CameraManagerGlobal: Connecting to camera service
09-30 20:44:25.994  3484  9564 I CameraManager: Using legacy camera HAL.
09-30 20:44:26.393  3484  9564 I CameraDeviceState: Legacy camera service transitioning to state CONFIGURING
09-30 20:44:26.396  3484  9601 I RequestThread-0: Configure outputs: 2 surfaces configured.
09-30 20:44:26.399  3484  9601 D Camera  : app passed NULL surface
09-30 20:44:26.404  3484  9601 I RequestThread-0: configureOutputs - set take picture size to 4128x3096
09-30 20:44:26.418  3484  9602 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.9_RB1__release_AU (I750f7f2fa6)
09-30 20:44:26.418  3484  9602 I Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.09.00.03
09-30 20:44:26.418  3484  9602 I Adreno-EGL: Build Date: 02/18/17 Sat
09-30 20:44:26.418  3484  9602 I Adreno-EGL: Local Branch: 
09-30 20:44:26.418  3484  9602 I Adreno-EGL: Remote Branch: quic/LA.BR.1.2.9_rb1.12
09-30 20:44:26.418  3484  9602 I Adreno-EGL: Local Patches: NONE
09-30 20:44:26.418  3484  9602 I Adreno-EGL: Reconstruct Branch: NOTHING
09-30 20:44:26.475  3484  9602 W Adreno-EGL: <qeglDrvAPI_eglQueryContext:4368>: EGL_BAD_ATTRIBUTE
09-30 20:44:26.501  3484  9564 I CameraDeviceState: Legacy camera service transitioning to state IDLE
09-30 20:44:26.512  3484  9564 I RequestQueue: Repeating capture request set.
09-30 20:44:26.514  3484  9564 I termux-api: preview started
09-30 20:44:26.523  3484  9601 W LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
09-30 20:44:26.525  3484  9601 W LegacyRequestMapper: Only received metering rectangles with weight 0.
09-30 20:44:26.976  3484  9602 I CameraDeviceState: Legacy camera service transitioning to state CAPTURING
09-30 20:44:27.015  3484  9564 I RequestQueue: Repeating capture request cancelled.
09-30 20:44:27.015  3484  9564 I termux-api: preview stoppend
09-30 20:44:27.016  3484  9564 I termux-api: Not using a front facing camera.
09-30 20:44:27.017  3484  9564 I termux-api: Sensor orientation: 90 degrees
09-30 20:44:27.019  3484  9564 I termux-api: Device orientation: 0 degrees
09-30 20:44:27.020  3484  9564 I termux-api: Returning JPEG orientation of 90 degrees
09-30 20:44:27.021  3484  9564 E Legacy-CameraDevice-JNI: LegacyCameraDevice_nativeGetSurfaceId: Could not retrieve native Surface from surface.
09-30 20:44:27.026  3484  9564 E termux-api: onConfigured() error in preview
09-30 20:44:27.026  3484  9564 E termux-api: android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): submitRequestList - configured surface is abandoned.
09-30 20:44:27.026  3484  9564 E termux-api:    at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:661)
09-30 20:44:27.026  3484  9564 E termux-api:    at android.hardware.camera2.impl.ICameraDeviceUserWrapper.submitRequestList(ICameraDeviceUserWrapper.java:86)
09-30 20:44:27.026  3484  9564 E termux-api:    at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:899)
09-30 20:44:27.026  3484  9564 E termux-api:    at android.hardware.camera2.impl.CameraDeviceImpl.capture(CameraDeviceImpl.java:788)
09-30 20:44:27.026  3484  9564 E termux-api:    at android.hardware.camera2.impl.CameraCaptureSessionImpl.capture(CameraCaptureSessionImpl.java:186)
09-30 20:44:27.026  3484  9564 E termux-api:    at com.termux.api.PhotoAPI.saveImage(PhotoAPI.java:186)
09-30 20:44:27.026  3484  9564 E termux-api:    at com.termux.api.PhotoAPI$3.onConfigured(PhotoAPI.java:170)
09-30 20:44:27.026  3484  9564 E termux-api:    at java.lang.reflect.Method.invoke(Native Method)
09-30 20:44:27.026  3484  9564 E termux-api:    at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
09-30 20:44:27.026  3484  9564 E termux-api:    at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
09-30 20:44:27.026  3484  9564 E termux-api:    at android.os.Handler.handleCallback(Handler.java:751)
09-30 20:44:27.026  3484  9564 E termux-api:    at android.os.Handler.dispatchMessage(Handler.java:95)
09-30 20:44:27.026  3484  9564 E termux-api:    at android.os.Looper.loop(Looper.java:154)
09-30 20:44:27.026  3484  9564 E termux-api:    at com.termux.api.PhotoAPI.takePicture(PhotoAPI.java:85)
09-30 20:44:27.026  3484  9564 E termux-api:    at com.termux.api.PhotoAPI.lambda$onReceive$0(PhotoAPI.java:49)
09-30 20:44:27.026  3484  9564 E termux-api:    at com.termux.api.-$$Lambda$PhotoAPI$TVeyrywhoGcxn5rY6HAcKkOPTo0.writeResult(lambda)
09-30 20:44:27.026  3484  9564 E termux-api:    at com.termux.api.util.ResultReturner.lambda$returnData$0(ResultReturner.java:133)
09-30 20:44:27.026  3484  9564 E termux-api:    at com.termux.api.util.-$$Lambda$ResultReturner$oCU8JqHW5HLMrNZa40ThjAWcwzo.run(lambda)
09-30 20:44:27.026  3484  9564 E termux-api:    at java.lang.Thread.run(Thread.java:762)
09-30 20:44:27.026  3484  9564 E termux-api: Caused by: android.os.ServiceSpecificException: submitRequestList - configured surface is abandoned.
09-30 20:44:27.026  3484  9564 E termux-api:    at android.hardware.camera2.legacy.LegacyCameraDevice.submitRequestList(LegacyCameraDevice.java:425)
09-30 20:44:27.026  3484  9564 E termux-api:    at android.hardware.camera2.legacy.CameraDeviceUserShim.submitRequestList(CameraDeviceUserShim.java:443)
09-30 20:44:27.026  3484  9564 E termux-api:    at android.hardware.camera2.impl.ICameraDeviceUserWrapper.submitRequestList(ICameraDeviceUserWrapper.java:84)
09-30 20:44:27.026  3484  9564 E termux-api:    ... 17 more
09-30 20:44:27.037  3484  9602 E Legacy-CameraDevice-JNI: LegacyCameraDevice_nativeGetSurfaceId: Could not retrieve native Surface from surface.
09-30 20:44:27.040  3484  9602 W SurfaceTextureRenderer: Surface abandoned, dropping frame.
09-30 20:44:27.040  3484  9602 W SurfaceTextureRenderer: android.hardware.camera2.legacy.LegacyExceptionUtils$BufferQueueAbandonedException
09-30 20:44:27.040  3484  9602 W SurfaceTextureRenderer:        at android.hardware.camera2.legacy.LegacyCameraDevice.getSurfaceId(LegacyCameraDevice.java:708)
09-30 20:44:27.040  3484  9602 W SurfaceTextureRenderer:        at android.hardware.camera2.legacy.LegacyCameraDevice.getSurfaceIds(LegacyCameraDevice.java:737)
09-30 20:44:27.040  3484  9602 W SurfaceTextureRenderer:        at android.hardware.camera2.legacy.SurfaceTextureRenderer.drawIntoSurfaces(SurfaceTextureRenderer.java:757)
09-30 20:44:27.040  3484  9602 W SurfaceTextureRenderer:        at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:105)
09-30 20:44:27.040  3484  9602 W SurfaceTextureRenderer:        at android.os.Handler.dispatchMessage(Handler.java:98)
09-30 20:44:27.040  3484  9602 W SurfaceTextureRenderer:        at android.os.Looper.loop(Looper.java:154)
09-30 20:44:27.040  3484  9602 W SurfaceTextureRenderer:        at android.os.HandlerThread.run(HandlerThread.java:61)
09-30 20:44:27.041  3484  9602 E Legacy-CameraDevice-JNI: LegacyCameraDevice_nativeGetSurfaceId: Could not retrieve native Surface from surface.
09-30 20:44:27.044  3484  9601 E RequestQueue: cancel failed: no repeating request exists for request id: 0
09-30 20:44:27.066  3484  3501 E BufferQueueProducer: [SurfaceTexture-1-3484-1] queueBuffer: BufferQueue has been abandoned
09-30 20:44:27.066  3484  3500 E BufferQueueProducer: [SurfaceTexture-1-3484-1] dequeueBuffer: BufferQueue has been abandoned
09-30 20:44:27.099  3484 16534 E BufferQueueProducer: [SurfaceTexture-1-3484-1] queueBuffer: BufferQueue has been abandoned
09-30 20:44:27.100  3484  3501 E BufferQueueProducer: [SurfaceTexture-1-3484-1] dequeueBuffer: BufferQueue has been abandoned
09-30 20:44:27.132  3484  3500 E BufferQueueProducer: [SurfaceTexture-1-3484-1] queueBuffer: BufferQueue has been abandoned
09-30 20:44:27.133  3484 16534 E BufferQueueProducer: [SurfaceTexture-1-3484-1] dequeueBuffer: BufferQueue has been abandoned
09-30 20:44:27.230  3484  3501 E BufferQueueProducer: [SurfaceTexture-1-3484-1] cancelBuffer: BufferQueue has been abandoned
09-30 20:44:27.230  3484  3500 E BufferQueueProducer: [SurfaceTexture-1-3484-1] cancelBuffer: BufferQueue has been abandoned
09-30 20:44:27.231  3484 16534 E BufferQueueProducer: [SurfaceTexture-1-3484-1] cancelBuffer: BufferQueue has been abandoned
09-30 20:44:27.231  3484  3501 E BufferQueueProducer: [SurfaceTexture-1-3484-1] cancelBuffer: BufferQueue has been abandoned
09-30 20:44:27.231  3484  3500 E BufferQueueProducer: [SurfaceTexture-1-3484-1] cancelBuffer: BufferQueue has been abandoned
09-30 20:44:27.231  3484 16534 E BufferQueueProducer: [SurfaceTexture-1-3484-1] cancelBuffer: BufferQueue has been abandoned
09-30 20:44:27.683  9555  9555 D AndroidRuntime: Shutting down VM
```
