### ISSUE TITLE
module-sles-source fails to initialize, module can not be loaded in pulseaudio (Termux didn't request microphone permission?)

### ISSUE THREAD

**Issue by felsd** [termux/termux-api#450]
**Problem description**
I am having problems with my microphone on my PC and want to use my Android phone's mic until I have resolved the issue. I installed pulseaudio on my phone via `pkg install pulseaudio` and enabled `module-sles-source` in `$PREFIX/etc/pulse/default.pa `:

```
...
### Make some devices default
#set-default-sink output
#set-default-source input
load-module module-sles-sink
load-module module-sles-source
#load-module module-aaudio-sink
```

When I start `pulseaudio` I get the following output:

```
~ $ pulseaudio
W: [pulseaudio] core.c: Failed to allocate shared posix-shm memory pool. Falling back to a normal memory pool.
E: [pulseaudio] module-sles-source.c: Failed to initialize OpenSL ES: error 9 at /home/builder/.termux-build/pulseaudio/src/src/modules/sles/module-sles-source.c:250
E: [pulseaudio] module.c: Failed to load module "module-sles-source" (argument: ""): initialization failed.
```

In `pactl list` I only have 1 source:

```
Source #1
	State: IDLE
	Name: OpenSL_ES_sink.monitor
	Description: Monitor of OpenSL ES Output
	Driver: module-sles-sink.c
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Owner Module: 15
	Mute: no
	Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	        balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor of Sink: OpenSL_ES_sink
	Latency: 0 usec, configured 125000 usec
	Flags: DECIBEL_VOLUME 
	Properties:
		device.description = "Monitor of OpenSL ES Output"
		device.class = "monitor"
		device.icon_name = "audio-input-microphone"
	Formats:
		pcm

```

Seems like `error 9` means "insufficient privileges". However, I can't give Termux the permission to acces the microphone in the Andorid Settings, and also assigning via `pm grant` fails:

```
:/data/data/com.termux/files/home # pm grant com.termux android.permission.RECORD_AUDIO
Security exception: Package com.termux has not requested permission android.permission.RECORD_AUDIO

java.lang.SecurityException: Package com.termux has not requested permission android.permission.RECORD_AUDIO
	at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:425)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2110)
	at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:122)
	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.grantRuntimePermission(PermissionManagerService.java:3072)
	at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:5830)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1955)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:230)
	at android.os.ShellCommand.exec(ShellCommand.java:104)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21946)
	at android.os.Binder.shellCommand(Binder.java:881)
	at android.os.Binder.onTransact(Binder.java:765)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4876)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4089)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
```

**Expected behavior**
`module-sles-source` gets loaded and the microphone shows up as a source in `pulseaudio`.

**Additional information**

```
~ $ termux-info 
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.14.185-Adi+ #1 SMP PREEMPT Wed Jun 24 13:29:33 CEST 2020 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Mi 9T
```

**Comment by felsd** [comment]
Figured it out! This is how I got it to work:
I knew `termux-api` was need but I only installed it via `pkg install termux-api`. After searching the Termux codebase for `android.permission.RECORD_AUDIO` I realized there's another Termux app. So I installed Termux:API from F-Droid and also reinstalled it via `pkg install` just in case. Then I gave Termux:API the microphone permission.

It's working fine now, closing this issue.
