### ISSUE TITLE
termux-wake-lock throws java errors

### ISSUE THREAD

**Issue by HMYang33** [termux/termux-api#584]
Android 5.1 （root)
termux : v0.79 offline bootstraps
apt repository : deb https://packages.termux.dev/termux-main-21/ stable main
(all packages upgraded from the repository above)

Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.dev/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on libera.chat

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root: pkg install root-repo

You are using legacy Termux environment.
Packages are unmaintained and will not
receive any updates.

$ termux-wake-lock
java.lang.ClassNotFoundException: Didn't find class "com.example.termuxam.Am" on path: DexPathList[[zip file "/data/data/com.termux/files/usr/libexec/termux-am/am.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        Suppressed: java.io.IOException: Failed to open oat file from dex location '/data/data/com.termux/files/usr/libexec/termux-am/am.apk'
                at dalvik.system.DexFile.openDexFileNative(Native Method)
                at dalvik.system.DexFile.openDexFile(DexFile.java:295)
                at dalvik.system.DexFile.<init>(DexFile.java:80)
                at dalvik.system.DexFile.<init>(DexFile.java:59)
                at dalvik.system.DexPathList.loadDexFile(DexPathList.java:262)
                at dalvik.system.DexPathList.makeDexElements(DexPathList.java:231)
                at dalvik.system.DexPathList.<init>(DexPathList.java:109)
                at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
                at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:38)
                at java.lang.ClassLoader.createSystemClassLoader(ClassLoader.java:128)
                at java.lang.ClassLoader.access$000(ClassLoader.java:65)
                at java.lang.ClassLoader$SystemClassLoader.<clinit>(ClassLoader.java:81)
                at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:137)
        Caused by: java.io.IOException: Failed to open oat file from /data/data/com.termux/files/usr/libexec/termux-am/arm64/am.odex (error Failed to open oat filename for reading: No such file or directory) (no dalvik_cache availible) and relocation failed.
                ... 13 more
        Caused by: java.io.IOException:
                ... 13 more
        Caused by: java.io.IOException: Failed to remove obsolete file from /data/dalvik-cache/arm64/data@data@com.termux@files@usr@libexec@termux-am@am.apk@classes.dex when searching for dex file /data/data/com.termux/files/usr/libexec/termux-am/am.apk: Permission denied
                ... 13 more
        Suppressed: java.lang.ClassNotFoundException: com.example.termuxam.Am
                at java.lang.Class.classForName(Native Method)
                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                ... 1 more
        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by HMYang33** [comment]
uninstall termux, clear dalvik , then resolved this problem.
卸载termux，清理dalvik，重新安装termux，问题解决
