### ISSUE TITLE
termux-fingerprint: Error in ResultReturner: java.io.IOException: Connection refused

### ISSUE THREAD

**Issue by errr-maxx** [termux/termux-api#607]
**Problem description**

When executing `termux-fingerprint -t 'Unlock'`
With this result:
```
{
  "errors": [],
  "failed_attempts": 3,
  "auth_result": "AUTH_RESULT_SUCCESS"
}
```
After some consecutive runs of the same command, I  start getting this result (alongside with Termux:API error notification):
```
{
  "errors": [
    "ERROR_TIMEOUT"
  ],
  "failed_attempts": 2,
  "auth_result": "AUTH_RESULT_SUCCESS"
}
```

**Steps to reproduce**

Run `termux-fingerprint -t 'Unlock'` 3-4 times in a row
Probably need to fail some unlock attempts

**Expected behavior**

There is no "ERROR_TIMEOUT" and no Termux:API error notifications

**Additional information**

* termux-api application version: 0.50.1+9e72088
* termux-api package version (installed through apt): 0.57
* Android OS version: 11
* Device model: Realme 7

## Report Info

**User Action**: `plugin execution command`  
**Sender**: `ResultReturner`  
**Report Timestamp**: `2023-06-05 10:05:13.818 UTC`  
##

## Termux:API Error

```
Error in ResultReturner:
java.io.IOException: Connection refused
	at android.net.LocalSocketImpl.connectLocal(Native Method)
	at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:262)
	at android.net.LocalSocket.connect(LocalSocket.java:148)
	at com.termux.api.util.ResultReturner.lambda$returnData$0(ResultReturner.java:161)
	at com.termux.api.util.-$$Lambda$ResultReturner$1wMz46asegPELp1xyZuz-rva9E4.run(Unknown Source:8)
	at java.lang.Thread.run(Thread.java:923)

```

## Termux:API App Info (Current)

**APP_NAME**: `Termux:API`  
**PACKAGE_NAME**: `com.termux.api`  
**VERSION_NAME**: `0.50.1+9e72088`  
**VERSION_CODE**: `51`  
**UID**: `10258`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**SE_PROCESS_CONTEXT**: `u:r:untrusted_app_27:s0:c2,c257,c512,c768`  
**SE_FILE_CONTEXT**: `u:object_r:app_data_file:s0:c2,c257,c512,c768`  
**SE_INFO**: `default:targetSdkVersion=28:complete`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0+11d8e4f`  
**VERSION_CODE**: `118`  
**UID**: `10258`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**SE_PROCESS_CONTEXT**: `u:r:untrusted_app_27:s0:c2,c257,c512,c768`  
**SE_FILE_CONTEXT**: `u:object_r:app_data_file:s0:c2,c257,c512,c768`  
**SE_INFO**: `default:targetSdkVersion=28:complete`  
**TERMUX_APP_PACKAGE_MANAGER**: -  
**TERMUX_APP_PACKAGE_VARIANT**: -  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

### Software

**OS_VERSION**: `4.14.313-ThunderStorm-2.4`  
**SDK_INT**: `30`  
**RELEASE**: `11`  
**ID**: `RP1A.200720.011`  
**DISPLAY**: `RMX2155_11_C.19`  
**INCREMENTAL**: `1659782254370`  
**SECURITY_PATCH**: `2022-08-05`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `realme`  
**BRAND**: `realme`  
**MODEL**: `RMX2155`  
**PRODUCT**: `RMX2155RU`  
**BOARD**: `RM6785`  
**HARDWARE**: `mt6785`  
**DEVICE**: `RMX2155L1`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

**Comment by 0m364** [comment]
This error message indicates that the Java application (in this case, Termux) is trying to connect to a server via a socket, but the connection is being refused. 

In other words, Termux is attempting to create a local connection to some service, but that service is either not running, not accepting connections, or cannot be reached at the provided socket address. 
Here are a few potential causes of this issue:

1. **The service Termux is trying to connect to isn't running**: If the service (possibly a server) that Termux is attempting to connect to isn't running, the connection would be refused. It's important to ensure that any necessary services or servers are active and properly functioning.

2. **Firewall or Security Settings**: Sometimes, a firewall or other security settings can prevent connections from being established. It's worth checking the device's security settings to ensure they're not blocking the connection.

3. **The socket address is wrong**: If the socket address that Termux is trying to connect to is incorrect, the connection would also be refused. It's crucial to ensure that the address is correct.

4. **Software bugs in Termux or the other service**: If there are bugs in either Termux or the service it's trying to connect to, these could cause intermittent connection issues.

Since this issue is intermittent, it might also be helpful to check what's happening on the device at the times when the issue occurs. There could be some other process or event that's interfering with the connection.

To troubleshoot this issue, you could consider these steps:

- Check the state of the service Termux is trying to connect to when the issue occurs. 
- Look into the device's security settings to ensure they're not blocking the connection.
- Verify the socket address being used for the connection.
- Check for updates or bug reports for Termux or the service it's trying to connect to.


most likely it is getting lost in an android subprocess check

**Comment by sumitshinde-84** [comment]
Hi @2096779623, I'm experiencing an issue with the fingerprint sensor on my Android device. When I run a command to list all available sensors, it doesn't show that the fingerprint sensor is available. I would greatly appreciate your help if you can assist me with this problem. Thank you

**Comment by 2096779623** [comment]
> Hi @2096779623, I'm experiencing an issue with the fingerprint sensor on my Android device. When I run a command to list all available sensors, it doesn't show that the fingerprint sensor is available. I would greatly appreciate your help if you can assist me with this problem. Thank you

Does `termux-sensor -l` have a touch sensor?
Does `termux-fingerprint` work fine?
Please provide `termux-info` output.
Don't ping any of the devs next time, someone will look at it.

**Comment by sumitshinde-84** [comment]
```{
  "sensors": [
    "ACCELEROMETER",
    "ORIENTATION",
    "LIGHT",
    "PROXIMITY",
    "SIGNIFICANT_MOTION",
    "STEP_DETECTOR",
    "STEP_COUNTER",
    "TILT_DETECTOR",
    "GLANCE_GESTURE",
    "pickup  Wakeup",
    "DEVICE_ORIENTATION",
    "STATIONARY_DETECT",
    "MOTION_DETECT",
    "STEP_DETECTOR_WAKEUP"
  ]
}``` hear is output and  I'll refrain from pinging the devs next time, and I appreciate someone looking into it

**Comment by 2096779623** [comment]
> hear is output and I'll refrain from pinging the devs next time, and I appreciate someone looking into it
> 
> ```
>   "sensors": [
>     "ACCELEROMETER",
>     "ORIENTATION",
>     "LIGHT",
>     "PROXIMITY",
>     "SIGNIFICANT_MOTION",
>     "STEP_DETECTOR",
>     "STEP_COUNTER",
>     "TILT_DETECTOR",
>     "GLANCE_GESTURE",
>     "pickup  Wakeup",
>     "DEVICE_ORIENTATION",
>     "STATIONARY_DETECT",
>     "MOTION_DETECT",
>     "STEP_DETECTOR_WAKEUP"
>   ]
> }``` 
> ```

What happens when you run `termux-fingerprint`?

**Comment by sumitshinde-84** [comment]
Termux ask me for authentication by fingerprint
