### ISSUE TITLE
arbitrary settings (system, not Termux)

### ISSUE THREAD

**Issue by Rudxain** [termux/termux-api#624]
**Feature description**
Add a command to get/set arbitrary settings from arbitrary categories, similarly to `adb shell settings`.

This will make Termux much more useful, and less dependent on automation apps.

**Reference implementation**

Have you checked if the feature is accessible through the Android API? Obviously, yes.
Do you know of other open-source apps that has a similar feature as the one you want? (Provide links)
- https://llamalab.com/automate/doc/block/system_setting_get.html
- https://llamalab.com/automate/doc/block/system_setting_set.html

**etc**
An alternative implementation is to "overload" the `settings` command in the same way that [`am` is "overloaded"](/termux/TermuxAm), but this would no longer be part of `termux-api`, it would have to be included in `termux-app`

**Comment by Rudxain** [comment]
Also for #425

**Comment by Benjamin-Loison** [comment]
Contrarily to reading, setting global setting leads to `java.lang.SecurityException: Permission denial, must have one of: [android.permission.WRITE_SECURE_SETTINGS]`.

<details>
<summary><code>adb logcat</code>:</summary>

```
03-09 04:10:29.866 27975 27975 D TermuxAPI.TermuxApiReceiver: Intent Received:
03-09 04:10:29.866 27975 27975 D TermuxAPI.TermuxApiReceiver: Intent { flg=0x10 cmp=com.termux.api/.TermuxApiReceiver (has extras) }
03-09 04:10:29.866 27975 27975 D TermuxAPI.TermuxApiReceiver: Bundle[
03-09 04:10:29.866 27975 27975 D TermuxAPI.TermuxApiReceiver: dump: `null`
03-09 04:10:29.866 27975 27975 D TermuxAPI.TermuxApiReceiver: socket_input: `4aacc6f8ef83ccd0-6d79-43a0-ae41-2548ccb0ab5b1e0364b65bb8`
03-09 04:10:29.866 27975 27975 D TermuxAPI.TermuxApiReceiver: socket_output: `f3706a9397b98687-6d79-42c4-a56a-d7e25f9d80dfc81c3d970c1`
03-09 04:10:29.866 27975 27975 D TermuxAPI.TermuxApiReceiver: api_method: `Accessibility`
03-09 04:10:29.866 27975 27975 D TermuxAPI.TermuxApiReceiver: ]
03-09 04:10:29.871 27975 27975 D TermuxAPI.AccessibilityAPI: onReceive
03-09 04:10:29.883 27975 27975 D TermuxAPI.AccessibilityAPI: setting: Benjamin Loison Fairphone 4 LineageOS
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: Error in TermuxApiReceiver:
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: java.lang.SecurityException: Permission denial, must have one of: [android.permission.WRITE_SECURE_SETTINGS]
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3373)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.os.Parcel.createException(Parcel.java:3357)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.os.Parcel.readException(Parcel.java:3340)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:225)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:177)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:764)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.provider.Settings$NameValueCache.putStringForUser(Settings.java:3660)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.provider.Settings$Global.putStringForUser(Settings.java:19445)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.provider.Settings$Global.putString(Settings.java:19281)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at com.termux.api.apis.AccessibilityAPI.onReceive(AccessibilityAPI.java:66)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at com.termux.api.TermuxApiReceiver.doWork(TermuxApiReceiver.java:89)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at com.termux.api.TermuxApiReceiver.onReceive(TermuxApiReceiver.java:66)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:5301)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2715)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.os.Handler.dispatchMessage(Handler.java:132)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.os.Looper.dispatchMessage(Looper.java:333)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.os.Looper.loopOnce(Looper.java:263)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.os.Looper.loop(Looper.java:367)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.app.ActivityThread.main(ActivityThread.java:9287)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at java.lang.reflect.Method.invoke(Native Method)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: Caused by: android.os.RemoteException: Remote stack trace:
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at com.android.providers.settings.SettingsProvider.enforceHasAtLeastOnePermission(SettingsProvider.java:2545)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1621)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at com.android.providers.settings.SettingsProvider.insertGlobalSetting(SettingsProvider.java:1575)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:496)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 	at android.content.ContentProvider.call(ContentProvider.java:2746)
03-09 04:10:29.889 27975 27975 E TermuxAPI.TermuxApiReceiver: 
03-09 04:10:29.912 27975 27975 D TermuxAPI.TermuxApiReceiver: Sending "Termux:API Error" notification.
03-09 04:10:29.921 27975 27975 D TermuxAPI.ReflectionUtils: Bypassing android hidden api reflection restrictions
03-09 04:10:30.028 27975 27975 E TermuxAPI.SettingsProviderUtils: Failed to get "device_config_sync_disabled" key value from settings "GLOBAL" namespace of type "INT"
03-09 04:10:30.081 27975 28043 D TermuxAPI.ResultReturner: Connecting to output socket "f3706a9397b98687-6d79-42c4-a56a-d7e25f9d80dfc81c3d970c1"
```
</details>

**Comment by Benjamin-Loison** [comment]
<details>
<summary>After <a href="https://github.com/Benjamin-Loison/termux-app/issues/94#issuecomment-4043603256">further investigations</a>, only some entries of <i>system</i> can be modified:</summary>

```
accelerometer_rotation: 0
alarm_alert: content://media/internal/audio/media/291?title=Hassium&canonical=1
apply_ramping_ringer: 0
dim_screen: 1
dtmf_tone: 1
end_button_behavior: 2
font_scale: 1.0
haptic_feedback_enabled: 0
mode_ringer_streams_affected: 422
mute_streams_affected: 111
next_alarm_formatted: 
notification_sound: content://media/internal/audio/media/138?title=Argon&canonical=1
ringtone: content://media/internal/audio/media/117?title=Orion&canonical=1
screen_brightness: 1
screen_brightness_mode: 0
screen_off_timeout: 60000
show_password: 1
sound_effects_enabled: 1
system_locales: en-FR,fr-FR
time_12_24: 24
user_rotation: 0
vibrate_when_ringing: 0
volume_alarm: 6
volume_bluetooth_sco: 7
volume_music: 5
volume_notification: 5
volume_ring: 5
volume_system: 7
volume_voice: 4
```
</details>

on my Fairphone 4 LineageOS 23.2.

Are you interested in me adding the ability to set these fields or they are to restrained to be interesting?

**Comment by Benjamin-Loison** [comment]
Well I needed write access to one of these entries, so I added write access to [pull/848](https://github.com/termux/termux-api/pull/848).

**Comment by Rudxain** [comment]
> Are you interested in me adding the ability to set these fields or they are to restrained to be interesting?

I think it's fine if some can't be set, that's what ADB is for. Ideally, if Termux has `WRITE_SECURE_SETTINGS`, then it should be possible to set more. Granting that permission only needs a 1-time ADB command
