### ISSUE TITLE
Does termux-call-log require root access?

### ISSUE THREAD

**Issue by siputra12** [termux/termux-api#697]
**Problem description**
Similar problem like #434 and #658
Im trying to use `termux-call-log` but output is empty,
when i try `termux-sms-list` its works fine

**What I've Tried**
Firstly, im using my other Phone with Root Access
and app from F-Droid version, the output shown all i expected.

But when i test from my Non-Root Phone, output is empty.
already try and updating Termux:App and Termux:API
with newest version from Github or F-Droid, but output still empty.

**Steps to reproduce**
```
termux-call-log
```

**Expected behavior**
Call log in json format

**Additional information**

* termux-api application version: 0.50.1
* termux-api package version (installed through apt): 0.58.0-1
* Android OS version: 14 (SDK 34)
* Device model: Asus Zenfone 10

**Comment by siputra12** [comment]
I found all this in logcat
```
08-06 20:48:19.268  8395 15848 E termux-api: Error in ResultReturner
08-06 20:48:19.268  8395 15848 E termux-api: java.lang.IllegalArgumentException: Invalid token LIMIT
08-06 20:48:19.268  8395 15848 E termux-api:    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
08-06 20:48:19.268  8395 15848 E termux-api:    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
08-06 20:48:19.268  8395 15848 E termux-api:    at android.content.ContentProviderProxy.query(ContentProviderNative.java:495)
08-06 20:48:19.268  8395 15848 E termux-api:    at android.content.ContentResolver.query(ContentResolver.java:1247)
08-06 20:48:19.268  8395 15848 E termux-api:    at android.content.ContentResolver.query(ContentResolver.java:1166)
08-06 20:48:19.268  8395 15848 E termux-api:    at android.content.ContentResolver.query(ContentResolver.java:1122)
08-06 20:48:19.268  8395 15848 E termux-api:    at com.termux.api.a1.b(Unknown Source:48)
08-06 20:48:19.268  8395 15848 E termux-api:    at com.termux.api.a1.a(Unknown Source:0)
08-06 20:48:19.268  8395 15848 E termux-api:    at com.termux.api.a1$a.b(Unknown Source:6)
08-06 20:48:19.268  8395 15848 E termux-api:    at com.termux.api.util.b$a.a(Unknown Source:10)
08-06 20:48:19.268  8395 15848 E termux-api:    at com.termux.api.util.b.b(Unknown Source:89)
08-06 20:48:19.268  8395 15848 E termux-api:    at com.termux.api.util.a.run(Unknown Source:8)
08-06 20:48:19.268  8395 15848 E termux-api:    at java.lang.Thread.run(Thread.java:1012)
```

**Comment by agnostic-apollo** [comment]
Closed by 11eff5658cae1a2f0f2031a5da8df9351d4cb9e5
