### ISSUE TITLE
termux-open does nothing

### ISSUE THREAD

**Issue by christianrondeau** [termux/termux-api#91]
`termux-open-url` works fine, but `termux-open` does nothing. No output and the $status is `0`.

There is a small delay though. I tried a png, a jpg and a txt, in `~/` and in `/`. 

I'm not sure what additional diagnostic to provide. 

    Termux version:
    <=0.48
    Installed Termux apps:
    Updatable packages:
    All packages up to date
    System information:
    Linux localhost 3.18.14-10780217 #1 SMP PREEMPT Fri Feb 24 13:45:03 KST 2017 aarch64 Android
    Termux-packages arch:
    aarch64
    Android version:
    7.0
    Device manufacturer:
    samsung
    Device model:
    SM-G935W8

Also, running termux-info also printed:

    android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:628)
        at android.os.BinderProxy.shellCommand(Binder.java:675)
        at com.android.commands.pm.Pm.runShellCommand(Pm.java:295)
        at com.android.commands.pm.Pm.runList(Pm.java:644)
        at com.android.commands.pm.Pm.run(Pm.java:130)
        at com.android.commands.pm.Pm.main(Pm.java:99)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:301)

**Comment by sdrausty** [comment]
`termux-open --chooser` did not install an APK. Termux:API add on was installed.

![screenshot_20170812-185630](https://user-images.githubusercontent.com/27742457/29245715-3fd9d93e-7fb1-11e7-938c-b1fe330665eb.png)

**Comment by Aman3832** [comment]
I have also termux-open not working 
Since I updated termux to its latest version , I can't open a file with termux-open. When I run the command its shows the app dialog , and when I click google photos to open it , it says 'media not found'.

**Comment by agnostic-apollo** [comment]
> Since I updated termux to its latest version , I can't open a file with termux-open

Check https://www.reddit.com/r/termux/comments/s266li/dev_termux_v01180_release/
